name: Functions Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Disabled by default; enable by setting repo variable ENABLE_FUNCTIONS_DEPLOY=true
    if: ${{ vars.ENABLE_FUNCTIONS_DEPLOY == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Firebase Tools
        run: npm i -g firebase-tools
      - name: Install functions deps
        working-directory: functions
        run: npm ci
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}